### ISSUE TITLE
Restful HTTP API

### ISSUE THREAD

**Issue by yayaa1006** [CSCWLab2015/nxt#2]

**Comment by yayaa1006** [comment]
<img width="567" alt="restful http apt 1" src="https://cloud.githubusercontent.com/assets/12039450/12516357/58b059c2-c12d-11e5-8233-8ad077559ccb.png">

**Comment by farshidtz** [comment]
Hey, the endpoint for Getting status is changed. Btw, this section of GitHub is for writing issues (problems). For images you can use the repository.
